project:
  type: website

website:
  title: "CSS@IPP â€” Tutorials and resources"
  page-footer: "![](./assets/general/crest-logo.png){height=100px}" 
  navbar:
    left:
      - text: BERTopic Tutorial
        href: pages/bertopic-tutorial.qmd
      - text: Information Extraction tutorial
        href: pages/information-extraction.qmd
    right:
      - href: https://www.css.cnrs.fr
        text: CSS@IPP website
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script>
          var _paq = window._paq = window._paq || [];
          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
          _paq.push(["setCookieDomain", "*.css-polytechnique.github.io"]);
          _paq.push(["disableCookies"]);
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
              var u="https://analyseweb.huma-num.fr/";
              _paq.push(['setTrackerUrl', u+'matomo.php']);
              _paq.push(['setSiteId', '615']);
              var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
              g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          })();
          </script>