project:
  type: website

website:
  title: "CSS@IPP â€” Tutorials and resources"
  page-footer: "![](./assets/general/crest-logo.png){height=100px}" 
  navbar:
    left:
      - text: BERTopic Tutorial
        href: pages/bertopic-tutorial.qmd
      - text: Information Extraction tutorial
        href: pages/information-extraction.qmd
    right:
      - href: https://www.css.cnrs.fr
        text: CSS@IPP website
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true